import type { Metadata } from "next";
import "./globals.css";
import TanStackProvider from "@/lib/tanstackQueryProvider";
import ThemeInitializer from "./ThemeInitializer";

export const metadata: Metadata = {
  title: "코드 탐정단",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ThemeInitializer />
        <TanStackProvider>{children}</TanStackProvider>
      </body>
    </html>
  );
}
